# docker compose file for the project
#
# Usage: docker-compose up
#        docker-compose up -d
#        docker-compose down
#        docker-compose build

version: '3.8'

services:
# our app services below:
  dotnet-svc:
    build:
      context: ./services/dotnet-svc
      dockerfile: Dockerfile
    image: go-api-svc

    ports:
      - "5010:5010"