# docker compose file for the project
#
# Usage: docker-compose up
#        docker-compose up -d
#        docker-compose down
#        docker-compose build

version: '3.8'
# our app services below:
services:
  nodejs-svc:
    build:
      context: ./services/nodejs-svc
      dockerfile: Dockerfile
    image: nodejs-svc
