# docker compose file for the project
#
# Usage: docker-compose up
#        docker-compose up -d
#        docker-compose down
#        docker-compose build

version: '3.8'

services:
  # our app services below:
  go-api-svc:
    build:
      context: ./services/go-api-svc
      dockerfile: Dockerfile
    image: go-api-svc
    ports:
      - "5001:5001"
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://localhost:5001/api/health || exit 1" ]
      interval: 15s
      timeout: 5s
      start_period: 10s #adjust as neccesary. 
      retries: 5
