# probably the most simple Component. https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-inmemory/
apiVersion: dapr.io/v1
kind: Component
metadata:
  name: pubsub
spec:
  type: pubsub.in-memory
  version: v1
  metadata: []